### ISSUE TITLE
R/W SMBIOS/DMI

### ISSUE THREAD

**Issue by WolsYang** [GeographicCone/UefiVarTool#2]
Hi,
    Is this tool able to search and edit dmi table?

**Comment by GeographicCone** [comment]
@WolsYang No, but there are other tools for that. For viewing, you can use [UEFI Shell](https://uefi.org/sites/default/files/resources/UEFI_Shell_2_2.pdf)'s `smbiosview` or [RW-Everything](http://rweverything.com/). To edit, there are vendor-specific tools, or you can dump the BIOS and edit the image, provided it can be reflashed.
